---

common_packages: [
  "coreutils",
  "cryptsetup",
  "tss2",
  "tpm2-tools",
  "softhsm",
  "libsofthsm2",
  "opensc",
  "protobuf-compiler",
  "protoc-gen-go",
  "protoc-gen-go-grpc",
]

pip_package: pip
pip_executable: "{{ 'pip3' if pip_package.startswith('python3') else 'pip' }}"
pip_install_packages: []

apt_install_packages: []

build_dir: ./
