---
- name: Create and open encrypted LUKS platform container
  community.crypto.luks_device:
    device: "{{ luks_device }}"
    name: "{{ luks_name }}"
    keyfile: "{{ luks_keyfile }}"
    state: "opened"

- name: Create LUKS container (remains unchanged if it already exists)
  community.crypto.luks_device:
    device: "/dev/loop5"
    state: "present"
    keyfile: "luks.key"